linters-settings:
  misspell:
    locale: US

  prealloc:
    simple: true
    range-loops: false # Report preallocation suggestions on range loops, true by default
    for-loops: false # Report preallocation suggestions on for loops, false by default

  revive:
    enable-all-rules: true
    rules:
      - name: banned-characters
        disabled: true
      - name: file-header
        disabled: true
      - name: cyclomatic
        disabled: true
      - name: get-return
        severity: warning
        disabled: true

      - name: cognitive-complexity
        severity: warning
        disabled: false
        arguments: [7]
      - name: line-length-limit
        severity: warning
        disabled: false
        arguments: [150]
      - name: function-length
        severity: warning
        disabled: false
        arguments: [20, 40]
      - name: max-public-structs
        severity: warning
        disabled: false
        arguments: [3]
      - name: function-result-limit
        severity: warning
        disabled: false
        arguments: [2]
      - name: argument-limit
        severity: warning
        disabled: false
        arguments: [5]
      - name: unhandled-error
        severity: warning
        disabled: false
        arguments:
          - "fmt.Printf"
          - "fmt.Println"
      - name: add-constant
        severity: warning
        disabled: false
        arguments:
          - allowStrs: '""'
            allowInts: "0,1"
            allowFloats: "0.0,0.,1.0,1."

linters:
  enable-all: false
  disable-all: true
  enable:
    - prealloc
    - errcheck
    - dupl
    - misspell
    - prealloc
    - revive
    - godot
