version: "3"
services:
  api-gateway:
    build: .
    image: go-template
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    depends_on:
      - "mongo"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "./data:/data/db"
